export const keys = {
     status: 'status',
     adminList: 'adminList',
     adminDetails: 'adminDetails',
     subscriptionStats: 'subscriptionStats',
     subscriptionList: 'subscriptionList',
     subscriptionDetails: 'subscriptionDetails',
     subscriptionListPaid: 'subscriptionListPaid',
     subscriptionListPaidDetails: 'subscriptionListPaidDetails',
     orderStats: 'orderStats',
     orderLogs: 'orderLogs',
     orderLogDetails: 'orderLogDetails',
     orderProductAuditQueue: 'orderProductAuditQueue',
     orderProductAuditQueueDetails: 'orderProductAuditQueueDetails',
     orderProductRejectionApproval: 'orderProductRejectionApproval',
     reportsStats: 'reportsStats',
     reportJob: 'reportJob',
     reportBusiness: 'reportBusiness',
     reportProduct: 'reportProduct',
     reportCommunity: 'reportCommunity',
     viewReportJob: 'viewReportJob',
     viewReportBusiness: 'viewReportBusiness',
     viewReportProduct: 'viewReportProduct',
     viewReportCommunity: 'viewReportCommunity',
     accountStats: 'accountStats',
     accountUsersList: 'accountUsersList',
     accountBusinessList: 'accountBusinessList',
     viewBusinessProfile: 'viewBusinessProfile',
     dashboardStats: 'dashboardStats',
     revenueGraph: 'revenueGraph',
     subscriptionChart: 'subscriptionChart',
     latestBusinesses: 'latestBusinesses',
     communitiesStats:'communitiesStats',
     communitiesList: 'communitiesList',

}